version: '3'

services:
  nginx:
    build:
      context: ./nginx
    volumes:
      - "${API_SOURCE_PATH}:/app"
    ports:
      - "${API_WEB_PORT}:80"
    depends_on:
      - api

  api:
    build:
      context: ./api
    volumes:
      - "${API_SOURCE_PATH}:/app"
    depends_on:
      - db

  db:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foo
      MYSQL_USER: foo
      MYSQL_PASSWORD: pass

volumes:
  mysql: ~
