version: '2'

services:
  nginx:
    build:
      context: ./nginx
    volumes:
      # - '${API_SOURCE_PATH}:/app' # default docker volume sync
      # - '${API_SOURCE_PATH}:/app:cached' # docker caching layer
      - app-sync:/app:nocopy # macOS: uncomment for docker-sync
    ports:
      - '${API_WEB_PORT}:80'
    depends_on:
      - api

  api:
    build:
      context: ./api
    volumes:
      # - '${API_SOURCE_PATH}:/app' # default docker volume sync
      # - '${API_SOURCE_PATH}:/app:cached' # docker caching layer
      - app-sync:/app:nocopy # macOS: docker-sync

# macOS: for docker-sync
volumes:
  app-sync:
    external: true
